# Generated by Django 2.2.24 on 2022-02-04 20:18

from django.db import migrations
from phonenumbers import is_valid_number, parse, format_number, PhoneNumberFormat


def purify_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_number = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(parsed_number):
            flat.owner_pure_phone = format_number(parsed_number, PhoneNumberFormat.E164)
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(purify_phonenumber)
    ]
