# Generated by Django 2.2.24 on 2022-02-10 22:22

from django.db import migrations


def set_flat_relations(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(
            owner=owner.name,
            owners_phonenumber=owner.phonenumber,
        )
        owner.flats.set(flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().update(flats=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220211_0055'),
    ]

    operations = [
        migrations.RunPython(set_flat_relations)
    ]
