# Generated by Django 2.2.24 on 2022-02-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220214_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='client',
        ),
    ]
